// Pure native compute ceiling for the 270-digit view -- NO HTTP, NO browser
// client. Replicates exactly what the server's compute_mandelbrot_perturb64 does
// (tile the image into `band`-row strips, one reference orbit + BLA table per
// strip via mandelbrot_perturb_bla64, run the strips over a rayon pool), but with
// a controlled thread count so we can compare against the HTTP-measured ~305
// rows/sec peak.
//
//   >> 305  : the server's ceiling is HTTP/serialization, not compute.
//   ~= 305  : the ceiling is the compute/memory subsystem (the ~big BLA table
//             blows past L3, random lookups, threads contend) -- and no amount
//             of server tuning gets past it without changing the algorithm.
//
// Digit arrays generated by replaying MB.html's convert() pipeline on the saved
// view (scratchpad/dump-digits.js), i.e. bit-identical input to what the client
// posts. Run: cargo run --release --example bench-server270
use mb_arith::*;
use rayon::prelude::*;
use std::time::Instant;

// 270-digit view: 640x480, maxIter 999999, 270 digits -> 59 u32 16-bit digits
const COLS: usize = 640;
const ROWS: usize = 480;
const MAX_ITER: i32 = 999999;
const XMIN_D: [u32; 59] = [65534, 9144, 56334, 65399, 61036, 36181, 257, 1520, 31979, 726, 42080, 47440, 30505, 25996, 33085, 56186, 41268, 2729, 37082, 20510, 29642, 54243, 494, 11023, 60337, 18160, 43047, 63242, 22687, 60542, 58540, 59579, 31229, 45064, 31714, 64337, 47505, 46615, 60801, 60416, 48996, 12290, 49801, 40032, 43770, 9477, 8346, 49041, 53253, 63324, 37473, 53474, 11377, 52735, 3314, 5177, 1821, 3770, 7728];
const DX_D: [u32; 59] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23715, 52199, 32807, 54371, 33869, 47010, 6081, 23754];
const YMAX_D: [u32; 59] = [0, 8, 21677, 19005, 52403, 48987, 16498, 46084, 63934, 24332, 32560, 53815, 2636, 12957, 1511, 18787, 58966, 62864, 15526, 44179, 39935, 52063, 47770, 2322, 60462, 35067, 19423, 58736, 7498, 19853, 28580, 16071, 50129, 24255, 40349, 60144, 14017, 49274, 6240, 40832, 16281, 18058, 16946, 30677, 8049, 60067, 29282, 43325, 8215, 43095, 10776, 11086, 11915, 32093, 13888, 12643, 45364, 25182, 12565];
const DY_D: [u32; 59] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 33557, 2974, 41963, 48032, 29450, 39680, 41176, 30281];

// Build the per-band (ymax, height) list for `rows` rows, advancing ymax by dy
// per row exactly as compute_mandelbrot_perturb64 does. `rows` is a parameter so
// we can test a TALLER image than the real 480 -- otherwise 480 rows cannot feed
// 32 threads with well-amortized bands (only 15 bands at band 32), and the
// throughput measures the image geometry, not the box.
fn make_bands(ymax: &[u64], dy: &[u64], band: usize, rows: usize) -> Vec<(Vec<u64>, usize)> {
    let mut dy_neg = vec![0u64; dy.len()];
    negate64(dy, &mut dy_neg);
    let mut bands = Vec::new();
    let mut y = ymax.to_vec();
    let mut r0 = 0;
    while r0 < rows {
        let h = band.min(rows - r0);
        bands.push((y.clone(), h));
        for _ in 0..h {
            incr64(&mut y, &dy_neg);
        }
        r0 += h;
    }
    bands
}

fn main() {
    let xmin = u32_to_limbs64(&XMIN_D);
    let dx = u32_to_limbs64(&DX_D);
    let ymax = u32_to_limbs64(&YMAX_D);
    let dy = u32_to_limbs64(&DY_D);
    // chunks: server's formula, 1 + ceil((u32_chunks-1)/4) u64 limbs
    let chunks = 1 + (XMIN_D.len() - 1 + 3) / 4;

    println!(
        "270-digit view {ROWS}x{COLS}, maxIter {MAX_ITER}, {} u32 digits -> {chunks} u64 limbs",
        XMIN_D.len()
    );
    println!("compare peak to the HTTP-measured server peak (~305 rows/sec)\n");

    let run = |band: usize, threads: usize, rows: usize| -> f64 {
        let bands = make_bands(&ymax, &dy, band, rows);
        let pool = rayon::ThreadPoolBuilder::new()
            .num_threads(threads)
            .build()
            .unwrap();
        // best of 2 -- orbit-dominated, low variance, but avoid a cold outlier
        let mut best = f64::INFINITY;
        for _ in 0..2 {
            let t = Instant::now();
            let _out: Vec<Vec<i32>> = pool.install(|| {
                bands
                    .par_iter()
                    .map(|(by, h)| {
                        let mut out = vec![0i32; h * COLS];
                        mandelbrot_perturb_bla64(&xmin, &dx, by, &dy, chunks, *h, COLS, MAX_ITER, &mut out);
                        out
                    })
                    .collect()
            });
            best = best.min(t.elapsed().as_secs_f64());
        }
        rows as f64 / best
    };

    println!("=== REAL image: {ROWS} rows (what the browser/server measured) ===");
    for &band in &[16usize, 32] {
        let nbands = ROWS.div_ceil(band);
        println!("band {band} rows ({nbands} bands = orbit builds for the {ROWS}-row image):");
        println!("  {:>7}  {:>10}  {:>18}", "threads", "rows/sec", "vs HTTP peak 305");
        for &th in &[1usize, 8, 16, 24, 32] {
            let rps = run(band, th, ROWS);
            println!("  {th:>7}  {rps:>10.1}  {:>17.2}x", rps / 305.0);
        }
        println!();
    }

    // Box ceiling, decoupled from image geometry: a TALL image so 32 threads each
    // get several well-amortized bands (band 32 -> 64 bands over 32 threads).
    const TALL: usize = 2048;
    println!("=== TALL image: {TALL} rows (isolates the 32-thread box ceiling) ===");
    for &band in &[16usize, 32, 64] {
        let nbands = TALL.div_ceil(band);
        println!("band {band} rows ({nbands} bands, {:.1} per thread at 32t):", nbands as f64 / 32.0);
        println!("  {:>7}  {:>10}  {:>18}", "threads", "rows/sec", "vs HTTP peak 305");
        for &th in &[16usize, 32] {
            let rps = run(band, th, TALL);
            println!("  {th:>7}  {rps:>10.1}  {:>17.2}x", rps / 305.0);
        }
        println!();
    }

    // What image-wide orbit SHARING would buy, single-threaded: one orbit + one
    // BLA table for all ROWS rows (mandelbrot_perturb_bla64 with rows=ROWS builds
    // exactly once), vs the per-band case that rebuilds per strip. Isolates the
    // build savings -- but note dc_max grows with the row span, so per-row BLA
    // skips shorten; this measures the NET, not just the build removed. A parallel
    // shared-orbit engine (build once, then par_iter the rows against the shared
    // table) needs a code change; this single-thread number bounds its base.
    println!("orbit-sharing potential (single thread, one orbit for all {ROWS} rows):");
    let mut out = vec![0i32; ROWS * COLS];
    let mut best = f64::INFINITY;
    for _ in 0..2 {
        let t = Instant::now();
        mandelbrot_perturb_bla64(&xmin, &dx, &ymax, &dy, chunks, ROWS, COLS, MAX_ITER, &mut out);
        best = best.min(t.elapsed().as_secs_f64());
    }
    let shared = ROWS as f64 / best;
    let per_band_1t = run(16, 1, ROWS);
    println!("  shared, 1 call        : {shared:>7.1} rows/sec");
    println!("  per-band 16, 1 thread : {per_band_1t:>7.1} rows/sec");
    println!("  single-thread speedup : {:>7.2}x from not rebuilding the orbit per strip", shared / per_band_1t);
}
