// Pure native compute ceiling for the 270-digit view -- NO HTTP, NO browser
// client. Replicates exactly what the server's compute_mandelbrot_perturb64 does
// (tile the image into `band`-row strips, one reference orbit + BLA table per
// strip via mandelbrot_perturb_bla64, run the strips over a rayon pool), but with
// a controlled thread count so we can compare against the HTTP-measured ~305
// rows/sec peak.
//
//   >> 305  : the server's ceiling is HTTP/serialization, not compute.
//   ~= 305  : the ceiling is the compute/memory subsystem (the ~big BLA table
//             blows past L3, random lookups, threads contend) -- and no amount
//             of server tuning gets past it without changing the algorithm.
//
// Digit arrays generated by replaying MB.html's convert() pipeline on the saved
// view (scratchpad/dump-digits.js), i.e. bit-identical input to what the client
// posts. Run: cargo run --release --example bench-server270
use mb_arith::*;
use rayon::prelude::*;
use std::time::Instant;

// 270-digit view: 640x480, maxIter 999999, 270 digits -> 59 u32 16-bit digits
const COLS: usize = 640;
const ROWS: usize = 480;
const MAX_ITER: i32 = 999999;
const XMIN_D: [u32; 59] = [65534, 9144, 56334, 65399, 61036, 36181, 257, 1520, 31979, 726, 42080, 47440, 30505, 25996, 33085, 56186, 41268, 2729, 37082, 20510, 29642, 54243, 494, 11023, 60337, 18160, 43047, 63242, 22687, 60542, 58540, 59579, 31229, 45064, 31714, 64337, 47505, 46615, 60801, 60416, 48996, 12290, 49801, 40032, 43770, 9477, 8346, 49041, 53253, 63324, 37473, 53474, 11377, 52735, 3314, 5177, 1821, 3770, 7728];
const DX_D: [u32; 59] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23715, 52199, 32807, 54371, 33869, 47010, 6081, 23754];
const YMAX_D: [u32; 59] = [0, 8, 21677, 19005, 52403, 48987, 16498, 46084, 63934, 24332, 32560, 53815, 2636, 12957, 1511, 18787, 58966, 62864, 15526, 44179, 39935, 52063, 47770, 2322, 60462, 35067, 19423, 58736, 7498, 19853, 28580, 16071, 50129, 24255, 40349, 60144, 14017, 49274, 6240, 40832, 16281, 18058, 16946, 30677, 8049, 60067, 29282, 43325, 8215, 43095, 10776, 11086, 11915, 32093, 13888, 12643, 45364, 25182, 12565];
const DY_D: [u32; 59] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 33557, 2974, 41963, 48032, 29450, 39680, 41176, 30281];

// Build the per-band (ymax, height) list for `rows` rows, advancing ymax by dy
// per row exactly as compute_mandelbrot_perturb64 does. `rows` is a parameter so
// we can test a TALLER image than the real 480 -- otherwise 480 rows cannot feed
// 32 threads with well-amortized bands (only 15 bands at band 32), and the
// throughput measures the image geometry, not the box.
fn make_bands(ymax: &[u64], dy: &[u64], band: usize, rows: usize) -> Vec<(Vec<u64>, usize)> {
    let mut dy_neg = vec![0u64; dy.len()];
    negate64(dy, &mut dy_neg);
    let mut bands = Vec::new();
    let mut y = ymax.to_vec();
    let mut r0 = 0;
    while r0 < rows {
        let h = band.min(rows - r0);
        bands.push((y.clone(), h));
        for _ in 0..h {
            incr64(&mut y, &dy_neg);
        }
        r0 += h;
    }
    bands
}

fn main() {
    let xmin = u32_to_limbs64(&XMIN_D);
    let dx = u32_to_limbs64(&DX_D);
    let ymax = u32_to_limbs64(&YMAX_D);
    let dy = u32_to_limbs64(&DY_D);
    // chunks: server's formula, 1 + ceil((u32_chunks-1)/4) u64 limbs
    let chunks = 1 + (XMIN_D.len() - 1 + 3) / 4;

    println!(
        "270-digit view {ROWS}x{COLS}, maxIter {MAX_ITER}, {} u32 digits -> {chunks} u64 limbs",
        XMIN_D.len()
    );
    println!("compare peak to the HTTP-measured server peak (~305 rows/sec)\n");

    let run = |band: usize, threads: usize, rows: usize| -> f64 {
        let bands = make_bands(&ymax, &dy, band, rows);
        let pool = rayon::ThreadPoolBuilder::new()
            .num_threads(threads)
            .build()
            .unwrap();
        // best of 2 -- orbit-dominated, low variance, but avoid a cold outlier
        let mut best = f64::INFINITY;
        for _ in 0..2 {
            let t = Instant::now();
            let _out: Vec<Vec<i32>> = pool.install(|| {
                bands
                    .par_iter()
                    .map(|(by, h)| {
                        let mut out = vec![0i32; h * COLS];
                        mandelbrot_perturb_bla64(&xmin, &dx, by, &dy, chunks, *h, COLS, MAX_ITER, &mut out);
                        out
                    })
                    .collect()
            });
            best = best.min(t.elapsed().as_secs_f64());
        }
        rows as f64 / best
    };

    println!("=== REAL image: {ROWS} rows (what the browser/server measured) ===");
    for &band in &[16usize, 32] {
        let nbands = ROWS.div_ceil(band);
        println!("band {band} rows ({nbands} bands = orbit builds for the {ROWS}-row image):");
        println!("  {:>7}  {:>10}  {:>18}", "threads", "rows/sec", "vs HTTP peak 305");
        for &th in &[1usize, 8, 16, 24, 32] {
            let rps = run(band, th, ROWS);
            println!("  {th:>7}  {rps:>10.1}  {:>17.2}x", rps / 305.0);
        }
        println!();
    }

    // Box ceiling, decoupled from image geometry: a TALL image so 32 threads each
    // get several well-amortized bands (band 32 -> 64 bands over 32 threads).
    const TALL: usize = 2048;
    println!("=== TALL image: {TALL} rows (isolates the 32-thread box ceiling) ===");
    for &band in &[16usize, 32, 64] {
        let nbands = TALL.div_ceil(band);
        println!("band {band} rows ({nbands} bands, {:.1} per thread at 32t):", nbands as f64 / 32.0);
        println!("  {:>7}  {:>10}  {:>18}", "threads", "rows/sec", "vs HTTP peak 305");
        for &th in &[16usize, 32] {
            let rps = run(band, th, TALL);
            println!("  {th:>7}  {rps:>10.1}  {:>17.2}x", rps / 305.0);
        }
        println!();
    }

    // What image-wide orbit SHARING would buy, single-threaded: one orbit + one
    // BLA table for all ROWS rows (mandelbrot_perturb_bla64 with rows=ROWS builds
    // exactly once), vs the per-band case that rebuilds per strip. Isolates the
    // build savings -- but note dc_max grows with the row span, so per-row BLA
    // skips shorten; this measures the NET, not just the build removed. A parallel
    // shared-orbit engine (build once, then par_iter the rows against the shared
    // table) needs a code change; this single-thread number bounds its base.
    println!("orbit-sharing potential (single thread, one orbit for all {ROWS} rows):");
    let mut out = vec![0i32; ROWS * COLS];
    let mut best = f64::INFINITY;
    for _ in 0..2 {
        let t = Instant::now();
        mandelbrot_perturb_bla64(&xmin, &dx, &ymax, &dy, chunks, ROWS, COLS, MAX_ITER, &mut out);
        best = best.min(t.elapsed().as_secs_f64());
    }
    let shared = ROWS as f64 / best;
    let per_band_1t = run(16, 1, ROWS);
    println!("  shared, 1 call        : {shared:>7.1} rows/sec");
    println!("  per-band 16, 1 thread : {per_band_1t:>7.1} rows/sec");
    println!("  single-thread speedup : {:>7.2}x from not rebuilding the orbit per strip\n", shared / per_band_1t);

    // --- PROTOTYPE: share the orbit, per-strip BLA tables (bla_strip) ---
    // Build ONE orbit for the whole image (reference at image center), then grind
    // each STRIP against it with a per-strip dc_max. Compare speed AND counts to
    // the shipping per-strip engine (mandelbrot_perturb_bla64, which rebuilds the
    // orbit at each strip's own center). Both are BLA approximations; the question
    // is whether sharing changes results and how much faster it is. STRIP = the
    // 4-row balance-friendly size the browser wants but currently can't afford.
    let strip = 4usize;
    println!("orbit-sharing prototype (bla_strip, {strip}-row strips, 1 thread):");

    // shipping per-strip engine: rebuild orbit per strip
    let mut out_ship = vec![0i32; ROWS * COLS];
    let ship_ms = {
        let mut dy_neg = vec![0u64; dy.len()];
        negate64(&dy, &mut dy_neg);
        let mut y = ymax.clone();
        let t = Instant::now();
        let mut r0 = 0;
        while r0 < ROWS {
            let h = strip.min(ROWS - r0);
            mandelbrot_perturb_bla64(&xmin, &dx, &y, &dy, chunks, h, COLS, MAX_ITER,
                &mut out_ship[r0 * COLS..(r0 + h) * COLS]);
            for _ in 0..h { incr64(&mut y, &dy_neg); }
            r0 += h;
        }
        t.elapsed().as_secs_f64() * 1e3
    };

    // shared orbit: one perturb_setup64 for the whole image, then bla_strip/strip
    let mut out_shared = vec![0i32; ROWS * COLS];
    let (build_ms, grind_ms) = {
        let tb = Instant::now();
        let (orbit, dx_f, dy_f, dcx0, _col_ref, img_row_ref) =
            perturb_setup64(&xmin, &dx, &ymax, &dy, chunks, ROWS, COLS, MAX_ITER);
        let build_ms = tb.elapsed().as_secs_f64() * 1e3;
        let tg = Instant::now();
        let mut r0 = 0;
        while r0 < ROWS {
            let h = strip.min(ROWS - r0);
            bla_strip(&orbit, dx_f, dy_f, dcx0, 0.0, img_row_ref, r0, h, COLS, MAX_ITER,
                &mut out_shared[r0 * COLS..(r0 + h) * COLS]);
            r0 += h;
        }
        (build_ms, tg.elapsed().as_secs_f64() * 1e3)
    };

    // Self-consistency: does per-strip bla_strip reproduce the WHOLE-IMAGE single
    // call (same image-center reference, one big dc_max table)? If yes, per-strip
    // tables are faithful and any vs-shipping delta is purely the reference choice
    // (image-center vs strip-center), not a bla_strip bug.
    let mut out_whole = vec![0i32; ROWS * COLS];
    mandelbrot_perturb_bla64(&xmin, &dx, &ymax, &dy, chunks, ROWS, COLS, MAX_ITER, &mut out_whole);
    let (mut whole_diff, mut whole_maxd) = (0usize, 0i32);
    for (a, b) in out_whole.iter().zip(out_shared.iter()) {
        let d = (a - b).abs();
        if d != 0 { whole_diff += 1; whole_maxd = whole_maxd.max(d); }
    }

    // agreement vs the shipping engine, with a row-distance diagnostic: if the
    // differences cluster in rows far from the image center, that's a single-far-
    // reference accuracy problem; if they're spread near the set boundary, it's
    // count-gradient noise (adjacent boundary pixels differ by 1000s anyway).
    let mut diff = 0usize;
    let mut maxd = 0i32;
    let mut sum_dist = 0f64; // avg |row - center| of differing pixels, in rows
    let center = ROWS as f64 / 2.0;
    let mut near_center = 0usize; // diffs within the central half of rows
    for (idx, (a, b)) in out_ship.iter().zip(out_shared.iter()).enumerate() {
        let d = (a - b).abs();
        if d != 0 {
            diff += 1;
            maxd = maxd.max(d);
            let row = (idx / COLS) as f64;
            sum_dist += (row - center).abs();
            if (row - center).abs() < ROWS as f64 / 4.0 { near_center += 1; }
        }
    }
    let total = ROWS * COLS;
    println!("  shipping (rebuild/strip): {ship_ms:>7.0} ms  -> {:>6.1} rows/sec", ROWS as f64 / (ship_ms / 1e3));
    println!("  shared orbit + bla_strip: build {build_ms:>4.0} ms + grind {grind_ms:>6.0} ms = {:>6.0} ms  -> {:>6.1} rows/sec",
        build_ms + grind_ms, ROWS as f64 / ((build_ms + grind_ms) / 1e3));
    println!("  speedup                 : {:>7.2}x", ship_ms / (build_ms + grind_ms));
    println!("  agreement vs shipping   : {diff}/{total} px differ ({:.4}%), max |delta| {maxd}",
        100.0 * diff as f64 / total as f64);
    if diff > 0 {
        println!("  diff distribution       : avg |row-center| {:.0} of {:.0} max; {:.0}% within central half",
            sum_dist / diff as f64, center, 100.0 * near_center as f64 / diff as f64);
    }
    println!("  bla_strip vs whole-image: {whole_diff}/{total} px differ, max |delta| {whole_maxd}  (0 = per-strip tables faithful)");
}
