/**
 * Mandelbrot
 * Does Mandelbrot computation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: william.wood@gsk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Mandelbrot);
  }
}(this, function(expect, Mandelbrot) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Mandelbrot.MandelbrotResults();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MandelbrotResults', function() {
    it('should create an instance of MandelbrotResults', function() {
      // uncomment below and update the code to test MandelbrotResults
      //var instance = new Mandelbrot.MandelbrotResults();
      //expect(instance).to.be.a(Mandelbrot.MandelbrotResults);
    });

  });

}));
