/**
 * Mandelbrot
 * Does Mandelbrot computation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: william.wood@gsk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiFailureResponse', 'model/MandelbrotCoords', 'model/MandelbrotResults'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ApiFailureResponse'), require('../model/MandelbrotCoords'), require('../model/MandelbrotResults'));
  } else {
    // Browser globals (root is window)
    if (!root.Mandelbrot) {
      root.Mandelbrot = {};
    }
    root.Mandelbrot.MandelbrotApi = factory(root.Mandelbrot.ApiClient, root.Mandelbrot.ApiFailureResponse, root.Mandelbrot.MandelbrotCoords, root.Mandelbrot.MandelbrotResults);
  }
}(this, function(ApiClient, ApiFailureResponse, MandelbrotCoords, MandelbrotResults) {
  'use strict';

  /**
   * Mandelbrot service.
   * @module api/MandelbrotApi
   * @version 1.0.0
   */

  /**
   * Constructs a new MandelbrotApi. 
   * @alias module:api/MandelbrotApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Iterate over pixels to determine if each is in the Mandelbrot set
     * 
     * @param {module:model/MandelbrotCoords} mandelbrotCoords Mandelbrot coordinates to compute
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/MandelbrotResults} and HTTP response
     */
    this.computeMandelbrotWithHttpInfo = function(mandelbrotCoords) {
      var postBody = mandelbrotCoords;

      // verify the required parameter 'mandelbrotCoords' is set
      if (mandelbrotCoords === undefined || mandelbrotCoords === null) {
        throw new Error("Missing the required parameter 'mandelbrotCoords' when calling computeMandelbrot");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = MandelbrotResults;

      return this.apiClient.callApi(
        '/mandelbrot/compute', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Iterate over pixels to determine if each is in the Mandelbrot set
     * 
     * @param {module:model/MandelbrotCoords} mandelbrotCoords Mandelbrot coordinates to compute
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/MandelbrotResults}
     */
    this.computeMandelbrot = function(mandelbrotCoords) {
      return this.computeMandelbrotWithHttpInfo(mandelbrotCoords)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
