/*
 * Mandelbrot
 *
 * Does Mandelbrot computation
 *
 * API version: V1.0
 * Contact: william.wood@gsk.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"net/http"
)

func ComputeMandelbrot(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
