/*
 * Mandelbrot
 *
 * Does Mandelbrot computation
 *
 * API version: V1.0
 * Contact: william.wood@gsk.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MandelbrotCoords struct {

	Y int64 `json:"y"`

	Xmin int64 `json:"xmin"`

	Dx int64 `json:"dx"`

	Columns int64 `json:"columns"`

	MaxIterations int32 `json:"maxIterations"`
}
