/*
 * Mandelbrot
 *
 * Does Mandelbrot computation
 *
 * API version: 1.0.0
 * Contact: william.wood@gsk.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MandelbrotCoords struct {

	Y float32 `json:"y"`

	Xmin float32 `json:"xmin"`

	Dx float32 `json:"dx"`

	Columns int32 `json:"columns"`

	MaxIterations int32 `json:"maxIterations"`
}
