/*
 * Mandelbrot
 *
 * Does Mandelbrot computation
 *
 * API version: 1.0.0
 * Contact: william.wood@gsk.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiFailureResponse struct {

	Message string `json:"message,omitempty"`
}
