/**
 * Mandelbrot
 * Does Mandelbrot computation
 *
 * OpenAPI spec version: V1.0
 * Contact: william.wood@gsk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiFailureResponse', 'model/MandelbrotCoords', 'model/MandelbrotResults', 'api/MandelbrotApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ApiFailureResponse'), require('./model/MandelbrotCoords'), require('./model/MandelbrotResults'), require('./api/MandelbrotApi'));
  }
}(function(ApiClient, ApiFailureResponse, MandelbrotCoords, MandelbrotResults, MandelbrotApi) {
  'use strict';

  /**
   * Does_Mandelbrot_computation.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Mandelbrot = require('index'); // See note below*.
   * var xxxSvc = new Mandelbrot.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Mandelbrot.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Mandelbrot.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Mandelbrot.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version V1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ApiFailureResponse model constructor.
     * @property {module:model/ApiFailureResponse}
     */
    ApiFailureResponse: ApiFailureResponse,
    /**
     * The MandelbrotCoords model constructor.
     * @property {module:model/MandelbrotCoords}
     */
    MandelbrotCoords: MandelbrotCoords,
    /**
     * The MandelbrotResults model constructor.
     * @property {module:model/MandelbrotResults}
     */
    MandelbrotResults: MandelbrotResults,
    /**
     * The MandelbrotApi service constructor.
     * @property {module:api/MandelbrotApi}
     */
    MandelbrotApi: MandelbrotApi
  };

  return exports;
}));
