/**
 * Mandelbrot
 * Does Mandelbrot computation
 *
 * OpenAPI spec version: V1.0
 * Contact: william.wood@gsk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mandelbrot) {
      root.Mandelbrot = {};
    }
    root.Mandelbrot.ApiFailureResponse = factory(root.Mandelbrot.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ApiFailureResponse model module.
   * @module model/ApiFailureResponse
   * @version V1.0
   */

  /**
   * Constructs a new <code>ApiFailureResponse</code>.
   * @alias module:model/ApiFailureResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ApiFailureResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiFailureResponse} obj Optional instance to populate.
   * @return {module:model/ApiFailureResponse} The populated <code>ApiFailureResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ApiFailureResponse.MessageEnum} message
   */
  exports.prototype['message'] = undefined;


  /**
   * Allowed values for the <code>message</code> property.
   * @enum {String}
   * @readonly
   */
  exports.MessageEnum = {
    /**
     * value: "CLIENT ERROR"
     * @const
     */
    "CLIENT ERROR": "CLIENT ERROR",
    /**
     * value: "SERVER ERROR"
     * @const
     */
    "SERVER ERROR": "SERVER ERROR"  };


  return exports;
}));


