/**
 * Mandelbrot
 * Does Mandelbrot computation
 *
 * OpenAPI spec version: V1.0
 * Contact: william.wood@gsk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mandelbrot) {
      root.Mandelbrot = {};
    }
    root.Mandelbrot.MandelbrotCoords = factory(root.Mandelbrot.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MandelbrotCoords model module.
   * @module model/MandelbrotCoords
   * @version V1.0
   */

  /**
   * Constructs a new <code>MandelbrotCoords</code>.
   * @alias module:model/MandelbrotCoords
   * @class
   * @param y {Number} 
   * @param xmin {Number} 
   * @param dx {Number} 
   * @param columns {Number} 
   * @param maxIterations {Number} 
   */
  var exports = function(y, xmin, dx, columns, maxIterations) {
    var _this = this;

    _this['y'] = y;
    _this['xmin'] = xmin;
    _this['dx'] = dx;
    _this['columns'] = columns;
    _this['maxIterations'] = maxIterations;
  };

  /**
   * Constructs a <code>MandelbrotCoords</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MandelbrotCoords} obj Optional instance to populate.
   * @return {module:model/MandelbrotCoords} The populated <code>MandelbrotCoords</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('y')) {
        obj['y'] = ApiClient.convertToType(data['y'], 'Number');
      }
      if (data.hasOwnProperty('xmin')) {
        obj['xmin'] = ApiClient.convertToType(data['xmin'], 'Number');
      }
      if (data.hasOwnProperty('dx')) {
        obj['dx'] = ApiClient.convertToType(data['dx'], 'Number');
      }
      if (data.hasOwnProperty('columns')) {
        obj['columns'] = ApiClient.convertToType(data['columns'], 'Number');
      }
      if (data.hasOwnProperty('maxIterations')) {
        obj['maxIterations'] = ApiClient.convertToType(data['maxIterations'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} y
   */
  exports.prototype['y'] = undefined;
  /**
   * @member {Number} xmin
   */
  exports.prototype['xmin'] = undefined;
  /**
   * @member {Number} dx
   */
  exports.prototype['dx'] = undefined;
  /**
   * @member {Number} columns
   */
  exports.prototype['columns'] = undefined;
  /**
   * @member {Number} maxIterations
   */
  exports.prototype['maxIterations'] = undefined;



  return exports;
}));


